name: afpmobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  iconify_design: ^1.0.1
  http: ^1.1.0
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/App_Logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/App_Logo.png

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/insignia/
    - assets/icons/
    - .env
